### ISSUE TITLE
Listed as 'vue-autocomplete' in package.json

### ISSUE THREAD

**Issue by haydenbbickerton** [BosNaufal/vue-loading-bar#2]
Not sure if you were gonna publish this in npm (you should!), but the package.json still says `vue-autocomplete`, which I'm guessing is leftover from your [vue-autocomplete](https://github.com/BosNaufal/vue-autocomplete) package.

**Comment by BosNaufal** [comment]
I missed it! Thank you @haydenbbickerton for reminding me... 
[It's](https://www.npmjs.com/package/vue-loading-bar) just published to NPM~ 
Enjoy the Code~
